# Generated by Django 5.0.1 on 2024-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(default='Nothing to see here.', max_length=1000),
        ),
    ]
